Update env_pysurf_fssh.yml
Update package list in env_pysurf_fssh.yml to avoid the following error:
$conda env create -f env_pysurf_fssh.yml
2 channel Terms of Service accepted
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - unsupported request
  - package libopenblas-0.3.30-openmp_hd680484_0 requires libgfortran5 >=14.3.0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ libgfortran5 =14.2.0 * is requested and can be installed;
├─ libgfortran =5.0.0 * does not exist (perhaps a typo or a missing channel);
├─ libopenblas =0.3.30 * is installable with the potential options
│  ├─ libopenblas 0.3.30 would require
│  │  └─ libgfortran5 >=14.3.0 *, which conflicts with any installable versions previously reported;
│  └─ libopenblas 0.3.30 would require
│     └─ llvm-openmp >=20.1.8 *, which can be installed;
└─ llvm-openmp =20.1.7 * is not installable because it conflicts with any installable versions previously reported.